version: "3.8"

services:  
  dojo_course_db_service:
    container_name: dojo_course_db_service
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=coding_dojo
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-config:/etc/postgresql
      - ./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dojo_course_network_private

  dojo_course_api:
    container_name: dojo_course_api
    build:
      context: ./api
    environment:
      - CONNECTION_STRING=postgresql://postgres:password@dojo_course_db_service:5432/coding_dojo
    networks:
      - dojo_course_network_private
      - dojo_course_network_public
    depends_on: 
      - dojo_course_db_service

  dojo_course_web:
    container_name: dojo_course_web
    build:
      context: ./web
    ports:
      - 80:3000
    environment:
      - API_URL=http://dojo_course_api:3001/data
    networks:
      - dojo_course_network_public
    depends_on: 
      - dojo_course_api

volumes:
  postgres-data:
  postgres-config:

networks:
  dojo_course_network_private:
    name: dojo_course_network_private
    driver: bridge

  dojo_course_network_public:
    name: dojo_course_network_public
    driver: bridge
